### ISSUE TITLE
"Start ads" not working ?

### ISSUE THREAD

**Issue by RomainOdeval** [ylorant/Hedgebot-admin#10]
We tried to use "Start ads" during a stream, weeks ago, but it didn't work : we had a cryptic "error occured" message.
Maybe it's broken or maybe we need a more specific message to know which condition was not here to launch ads.

**Comment by ylorant** [comment]
I'll have to check the Twitch API again, but sometimes the API doesn't give out clear answers on why an ad hasn't been able to be started.

**Comment by RomainOdeval** [comment]
Since last year, lot of work have been done. "Start ads" have been modified too.
So we close this issue.
