### ISSUE TITLE
Hosting & Raiding

### ISSUE THREAD

**Issue by RomainOdeval** [ylorant/Hedgebot-admin#11]
Some improvements : update "stream control" plugin to have to new options.
* One with a text box and a button "Host it !" to host a channel (not necesseraly a saved one)
* One with a text box and a button "Raid it !" to raid a channel (not necesseraly a saved one)

Maybe add a right for each option ? To not allow everybody to use that.
If so, turn those options to "disable" and an info about it.

**Comment by ylorant** [comment]
Done in commit 5132d48210c697fd343f466a7bf8187d34f301da
